import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Compass, Sparkles } from 'lucide-react';
import TripSummary from './TripSummary';
import DayAccordion from './DayAccordion';
import ActionToolbar from './ActionToolbar';
import PlaceDrawer from '../places/PlaceDrawer';
import EmergencyModal from './EmergencyModal';
import { ApiService } from '../../services/apiService';

export default function ItineraryDashboard({
  itinerary,
  userParams = {},
  onNewTrip,
  onEditForm,
  onRegenerate,
  isRegenerating = false,
}) {
  // Maintain persistent live React state for interactive edits (Milestone 5)
  const [tripData, setTripData] = useState(itinerary);

  // Sync state if a brand new itinerary is generated by parent
  useEffect(() => {
    if (itinerary) {
      setTripData(itinerary);
    }
  }, [itinerary]);

  // Multi-day accordion state: Day 1 (index 0) open by default, all remaining collapsed; multiple can remain open simultaneously
  const [expandedDays, setExpandedDays] = useState({ 0: true });

  // State for interactive right-side place drawer
  const [activePlaceQuery, setActivePlaceQuery] = useState(null);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  // State for centered Emergency Support Modal
  const [isEmergencyOpen, setIsEmergencyOpen] = useState(false);

  // Loading indicator keys for AI replacing or regenerating
  const [replacingKey, setReplacingKey] = useState('');
  const [regeneratingDayIndex, setRegeneratingDayIndex] = useState(null);

  if (!tripData || !Array.isArray(tripData.dailyItinerary)) {
    return null;
  }

  const handleToggleDay = (index) => {
    setExpandedDays((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  const handleOpenPlaceDrawer = (placeName) => {
    if (!placeName) return;
    setActivePlaceQuery(placeName);
    setIsDrawerOpen(true);
  };

  // 1. Delete single activity from a day's timeline
  const handleDeleteActivity = (dayIndex, activityIndex) => {
    setTripData((prev) => {
      const updatedDays = [...prev.dailyItinerary];
      const targetDay = { ...updatedDays[dayIndex] };
      if (Array.isArray(targetDay.timeline)) {
        targetDay.timeline = targetDay.timeline.filter((_, idx) => idx !== activityIndex);
      }
      updatedDays[dayIndex] = targetDay;
      return { ...prev, dailyItinerary: updatedDays };
    });
  };

  // 2. Intra-day Drag and Drop Reordering
  const handleReorderActivities = (dayIndex, fromIndex, toIndex) => {
    if (fromIndex === toIndex || fromIndex < 0 || toIndex < 0) return;
    setTripData((prev) => {
      const updatedDays = [...prev.dailyItinerary];
      const targetDay = { ...updatedDays[dayIndex] };
      if (Array.isArray(targetDay.timeline)) {
        const items = [...targetDay.timeline];
        const [movedItem] = items.splice(fromIndex, 1);
        items.splice(toIndex, 0, movedItem);
        targetDay.timeline = items.map((act) => ({ ...act }));
      }
      updatedDays[dayIndex] = targetDay;
      return { ...prev, dailyItinerary: updatedDays };
    });
  };

  // 2b. Reorder Entire Days Up or Down
  const handleMoveDay = (fromIndex, toIndex) => {
    if (
      fromIndex === toIndex ||
      fromIndex < 0 ||
      toIndex < 0 ||
      toIndex >= tripData.dailyItinerary.length
    )
      return;
    const updatedDays = [...tripData.dailyItinerary];
    const [movedDay] = updatedDays.splice(fromIndex, 1);
    updatedDays.splice(toIndex, 0, movedDay);

    // Keep days chronologically numbered while retaining all reordered activities and customizations
    const reorderedDays = updatedDays.map((d, idx) => ({ ...d, dayNumber: idx + 1 }));
    const newTripData = { ...tripData, dailyItinerary: reorderedDays };

    // Instantly update UI state
    setTripData(newTripData);

    // Refresh & regenerate itinerary around new day order as baseline
    if (onRegenerate) {
      onRegenerate(newTripData);
    }
  };

  // 3. Replace single activity via Gemini AI without touching rest of itinerary
  const handleReplaceActivity = async (dayIndex, activityIndex, currentActivity) => {
    const key = `${dayIndex}-${activityIndex}`;
    setReplacingKey(key);
    try {
      const response = await ApiService.replaceActivity({
        activity: currentActivity,
        destination: tripData.destination || userParams.destination || '',
        budget: tripData.budget || userParams.budget || 'moderate',
        travelStyle: tripData.travelStyle || userParams.travelStyle || 'travel',
        interests: tripData.interests || userParams.interests || 'sightseeing',
        notes: userParams.notes || '',
      });
      const newActivity =
        response?.activity || response?.data?.activity || response?.data || response;
      if (newActivity && (newActivity.title || newActivity.time)) {
        setTripData((prev) => {
          const updatedDays = [...prev.dailyItinerary];
          const targetDay = { ...updatedDays[dayIndex] };
          if (Array.isArray(targetDay.timeline)) {
            const items = [...targetDay.timeline];
            items[activityIndex] = { ...newActivity };
            targetDay.timeline = items;
          }
          updatedDays[dayIndex] = targetDay;
          return { ...prev, dailyItinerary: updatedDays };
        });
      }
    } catch (err) {
      console.error('Failed to replace activity:', err);
      alert('Could not generate an AI replacement right now. Please try again.');
    } finally {
      setReplacingKey('');
    }
  };

  // 4. Regenerate a single day schedule without regenerating whole trip
  const handleRegenerateDay = async (dayIndex, currentDay) => {
    setRegeneratingDayIndex(dayIndex);
    try {
      const response = await ApiService.regenerateDay({
        dayNumber: currentDay.dayNumber || dayIndex + 1,
        theme: currentDay.theme || 'Explore Highlights',
        destination: tripData.destination || userParams.destination || '',
        budget: tripData.budget || userParams.budget || 'moderate',
        travelStyle: tripData.travelStyle || userParams.travelStyle || 'travel',
        interests: tripData.interests || userParams.interests || 'sightseeing',
        notes: userParams.notes || '',
        existingDay: currentDay,
      });
      const newDay = response?.day || response?.data?.day;
      if (newDay && newDay.timeline) {
        setTripData((prev) => {
          const updatedDays = [...prev.dailyItinerary];
          updatedDays[dayIndex] = newDay;
          return { ...prev, dailyItinerary: updatedDays };
        });
      }
    } catch (err) {
      console.error('Failed to regenerate day:', err);
      alert('Could not regenerate this day right now. Please try again.');
    } finally {
      setRegeneratingDayIndex(null);
    }
  };

  const currentDestination = tripData.destination || userParams.destination || '';

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-5xl mx-auto px-2 sm:px-4 py-3 sm:py-8 overflow-x-hidden"
      id="itinerary-dashboard"
    >
      {/* Top Personalized Summary Card (Updates dynamically as edits occur) */}
      <TripSummary itinerary={tripData} userParams={userParams} />

      {/* Main Itinerary Section Header */}
      <div className="max-w-4xl mx-auto my-8 flex flex-col sm:flex-row items-center justify-between gap-4 border-b border-slate-800 pb-5 text-center sm:text-left">
        <div>
          <h2 className="text-2xl sm:text-3xl font-display font-extrabold text-white tracking-tight flex items-center justify-center sm:justify-start gap-2.5">
            <Compass className="h-6 w-6 text-sky-400" />
            <span>Your Interactive Itinerary</span>
          </h2>
          <p className="text-slate-400 text-xs sm:text-sm mt-1">
            Reorder activities via drag handles, replace items with AI, or regenerate individual
            days.
          </p>
        </div>

        <div className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-slate-900 border border-slate-800 text-indigo-300 text-xs font-semibold shadow-inner">
          <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
          <span>
            {tripData.dailyItinerary.length} {tripData.dailyItinerary.length === 1 ? 'Day' : 'Days'}
          </span>
        </div>
      </div>

      {/* Daily Accordions Collection */}
      <div className="space-y-6 max-w-4xl mx-auto mb-12">
        {tripData.dailyItinerary.map((day, index) => (
          <DayAccordion
            key={day.dayNumber || index}
            day={day}
            dayIndex={index}
            isOpen={Boolean(expandedDays[index])}
            onToggle={() => handleToggleDay(index)}
            onPlaceClick={handleOpenPlaceDrawer}
            onDeleteActivity={handleDeleteActivity}
            onReplaceActivity={handleReplaceActivity}
            onRegenerateDay={handleRegenerateDay}
            onReorderActivities={handleReorderActivities}
            onMoveDayUp={() => index > 0 && handleMoveDay(index, index - 1)}
            onMoveDayDown={() =>
              index < tripData.dailyItinerary.length - 1 && handleMoveDay(index, index + 1)
            }
            isFirstDay={index === 0}
            isLastDay={index === tripData.dailyItinerary.length - 1}
            onOpenEmergency={() => setIsEmergencyOpen(true)}
            isRegeneratingDay={regeneratingDayIndex === index}
            replacingKey={replacingKey}
          />
        ))}
      </div>

      {/* Smart Regeneration Informational Notice */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, delay: 0.1 }}
        className="w-full max-w-4xl mx-auto -mb-8 mt-4 p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-slate-900/90 via-slate-900/70 to-slate-900/90 border border-slate-800/80 shadow-md flex items-center gap-3.5 text-left"
      >
        <div className="w-10 h-10 rounded-xl bg-indigo-500/15 border border-indigo-500/30 text-indigo-400 flex items-center justify-center flex-shrink-0">
          <Sparkles className="h-5 w-5 text-indigo-400 animate-pulse" />
        </div>
        <p className="text-xs sm:text-sm text-slate-300 font-medium leading-relaxed">
          <strong className="text-white">Smart AI Regeneration:</strong> Future itinerary
          generations will use your current customized itinerary as the starting point. Your edits
          help the AI create better recommendations.
        </p>
      </motion.div>

      {/* Single Action Toolbar at the End of the Itinerary */}
      <ActionToolbar
        onNewTrip={onNewTrip}
        onEditForm={onEditForm}
        onRegenerate={() => onRegenerate && onRegenerate(tripData)}
        isRegenerating={isRegenerating}
      />

      {/* Interactive Right-Side Information Drawer */}
      <PlaceDrawer
        isOpen={isDrawerOpen}
        onClose={() => setIsDrawerOpen(false)}
        placeQuery={activePlaceQuery}
        destination={currentDestination}
      />

      {/* Centered Emergency Support Assistance Modal */}
      <EmergencyModal
        isOpen={isEmergencyOpen}
        onClose={() => setIsEmergencyOpen(false)}
        destination={currentDestination}
        emergencyInfo={tripData.destinationEmergencyInfo || {}}
      />
    </motion.div>
  );
}
